version: '3.7'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"  
    depends_on:
      - db
    restart: always

  frontend:
    build: ./client
    ports:
      - "5173:3000" 
    depends_on:
      - backend
    restart: always

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: